DFIB-99: added css linter and fixed warnings into css files
spryker/sable-for-zed pull request #15
Opened 2020-01-03 14:09 UTC by andrew-maslov

Ticket: https://spryker.atlassian.net/browse/DFIB-106

2020-01-10 11:19 UTC, supproduction requested changes

2020-01-10 11:19 UTC, supproduction commented on lib/stylelint.js
> +    formatter: "string",
Please, check will check `scss` files inside node_modules

2020-01-14 11:21 UTC, andrew-maslov commented on lib/stylelint.js
> +    formatter: "string",
Checked, node_modules ignored by default

2020-01-15 14:37 UTC, supproduction approved these changes

2020-07-13 14:56 UTC, tolerants approved these changes

2020-07-13 14:56 UTC, merged