CC-7758 Replace 'uglifyjs-webpack-plugin' to 'terser-webpack-plugin' dependency
spryker/sable-for-zed pull request #19
Opened 2020-01-17 13:02 UTC by andrew-maslov

Ticket: https://spryker.atlassian.net/browse/CC-7758

2020-01-17 13:30 UTC, supproduction approved these changes

2020-01-23 10:44 UTC, danilmoro3 approved these changes

2020-09-22 09:55 UTC, tolerants requested changes

2020-09-22 09:55 UTC, tolerants commented on package.json
> +    "node": ">=12.18.2",
Please revert these changes.

2020-09-22 09:55 UTC, tolerants commented on package.json
> +    "npm": ">=6.14.5"
And here.

2020-09-22 13:11 UTC, tolerants approved these changes

2020-09-22 13:21 UTC, merged