SUPESC-239: Node-sass to Dart-sass replacement
spryker/sable-for-zed pull request #33
Opened 2021-01-28 10:40 UTC by zamlely

## PR Description

Ticket: https://spryker.atlassian.net/browse/SUPESC-239

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-02-01 09:14 UTC, andrew-maslov commented on package.json
> +    "sass": "^1.32.5",
```suggestion
    "sass": "~1.32.5",
```

2021-02-05 15:42 UTC, andrew-maslov approved these changes

2021-02-24 08:46 UTC, tolerants approved these changes

2021-07-05 11:48 UTC, tolerants requested changes

2021-07-05 11:48 UTC, tolerants commented on package.json
> +    "sass-loader": "~8.0.0",
Please check if we can update to the latest version `12.1.0`.

2021-07-05 11:48 UTC, tolerants commented on package.json
> +    "sass": "~1.32.6",
Please check if we can update to the latest version `1.35.1`.

2022-03-17 19:29 UTC, tolerants approved these changes

2022-03-18 10:47 UTC, merged