TE-535: Changed globby to async approach
spryker/sable-for-zed pull request #4
Opened 2018-12-24 11:20 UTC by supproduction

https://spryker.atlassian.net/browse/TE-535

2019-01-04 15:27 UTC, ghost requested changes

2019-01-04 15:27 UTC, ghost commented on lib/webpack.config.js
> +    const etryPromise = oryx.find(settings.entry);
change into `entryPromise `

2019-01-04 15:27 UTC, ghost commented on lib/webpack.config.js
> +    return await Promise.all([modulesPromise, etryPromise]).then(pathes => {
change into `paths`

2019-01-04 15:27 UTC, ghost commented on lib/webpack.config.js
> +    return await Promise.all([modulesPromise, etryPromise]).then(pathes => {
1. why do you mix `await` and `then`? Async/awai, to my understanding, are design to prevent the callback hell/nesting of simple promises, keep the code clean and linear, and allow try/catch on asyn portions of code. I saw this pattern everywhere in this (and others) PR. Can you give me and explanation why? Otherwise I need you to refactor the code to remove the `then` part and transform the code according to async/await specs.

The only usecase for `then` is when execution of multiple async operation must be performed in parallel, as pointed out here: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

If you need to catch the error instead of throwing it above, use the last example here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await

2. Instead of relying on `paths[index]` that is not informative as much as dangerous, use a destructured assignment (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) like:

`const [a, b] = await Promise.all([A, B])`

2019-01-04 15:27 UTC, ghost commented on lib/webpack.config.js
> +                modules: pathes[0].concat([
better to use the spread operator here

2019-01-04 15:27 UTC, ghost commented on lib/webpack.config.js
> +        log.error(error, 'imposible to resolve pathes promises');
log message is grammatically incorrect, and is it necessary here? If so, please provide some more info about the context and use try catch and manage the error or throw it above

2019-01-08 11:06 UTC, supproduction commented on lib/webpack.config.js
> +    const etryPromise = oryx.find(settings.entry);
Fixed

2019-01-08 11:06 UTC, supproduction commented on lib/webpack.config.js
> +    return await Promise.all([modulesPromise, etryPromise]).then(pathes => {
Fixed

2019-01-08 11:06 UTC, supproduction commented on lib/webpack.config.js
> +                modules: pathes[0].concat([
Fixed

2019-01-08 11:07 UTC, supproduction commented on lib/webpack.config.js
> +        log.error(error, 'imposible to resolve pathes promises');
Removed error message from this function

2019-01-08 15:09 UTC, ghost approved these changes

2019-01-08 15:10 UTC, abelspry commented on build.js
> +configurationPromise
can you change this into `api.getConfiguration(api.settings)` directly? Sorry, I fogot to mention before.

2019-01-08 16:25 UTC, supproduction commented on build.js
> +configurationPromise
Fixed

2019-01-08 16:44 UTC, ghost approved these changes

2019-01-09 10:30 UTC, merged