TE-911: Changed webpack.config to made jq plugins external
spryker/sable-for-zed pull request #5
Opened 2019-01-03 15:51 UTC by supproduction

https://github.com/spryker/spryker/pull/4687

2019-01-03 16:09 UTC, danilmoro3 approved these changes

2019-01-17 10:38 UTC, ghost requested changes
This solution requires a deeper analysis as it leads to direct dependency between deps and tool. Not very fond of it. Probably DLL might be an alternative.

2019-01-17 10:38 UTC, ghost commented on package.json
> +    "uglify-js": "^3.4.9",
enforce `~3.4.9`

2019-01-31 16:01 UTC, ghost approved these changes

2019-02-01 10:43 UTC, closed without merging

2019-02-01 10:44 UTC, abelspry commented
Closed due to no functional code in PR.